[package]
name = "hid-bpf-uclogic-test"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
cc = "1.2.27"

[dev-dependencies]
hex = { version = "0.4.3", default-features = false, features = ["std"] }
insta = { version = "1.43.1", default-features = false }
